title: IT thoughts...
author:
  name: Joseph Ziegler
  email: joseph@josephziegler.com
description:
  Test page
baseurl: "/"
url: blog.josephziegler.com/testrepo
github_username:  zigsphere

minima:
  skin: dark  # having no effect

theme: minima
